<?php

use Illuminate\Database\Seeder;
use App\Models\City;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            [ 'description' => 'EL ENCANTO', 'department_id' => '1'],
            [ 'description' => 'LA CHORRERA', 'department_id' => '1'],
            [ 'description' => 'LA PEDRERA', 'department_id' => '1'],
            [ 'description' => 'LA VICTORIA', 'department_id' => '1'],
            [ 'description' => 'LETICIA', 'department_id' => '1'],
            [ 'description' => 'MIRITI', 'department_id' => '1'],
            [ 'description' => 'PUERTO ALEGRIA', 'department_id' => '1'],
            [ 'description' => 'PUERTO ARICA', 'department_id' => '1'],
            [ 'description' => 'PUERTO NARIÑO', 'department_id' => '1'],
            [ 'description' => 'PUERTO SANTANDER', 'department_id' => '1'],
            [ 'description' => 'TURAPACA', 'department_id' => '1'],
            [ 'description' => 'ABEJORRAL', 'department_id' => '2'],
            [ 'description' => 'ABRIAQUI', 'department_id' => '2'],
            [ 'description' => 'ALEJANDRIA', 'department_id' => '2'],
            [ 'description' => 'AMAGA', 'department_id' => '2'],
            [ 'description' => 'AMALFI', 'department_id' => '2'],
            [ 'description' => 'ANDES', 'department_id' => '2'],
            [ 'description' => 'ANGELOPOLIS', 'department_id' => '2'],
            [ 'description' => 'ANGOSTURA', 'department_id' => '2'],
            [ 'description' => 'ANORI', 'department_id' => '2'],
            [ 'description' => 'ANTIOQUIA', 'department_id' => '2'],
            [ 'description' => 'ANZA', 'department_id' => '2'],
            [ 'description' => 'APARTADO', 'department_id' => '2'],
            [ 'description' => 'ARBOLETES', 'department_id' => '2'],
            [ 'description' => 'ARGELIA', 'department_id' => '2'],
            [ 'description' => 'ARMENIA', 'department_id' => '2'],
            [ 'description' => 'BARBOSA', 'department_id' => '2'],
            [ 'description' => 'BELLO', 'department_id' => '2'],
            [ 'description' => 'BELMIRA', 'department_id' => '2'],
            [ 'description' => 'BETANIA', 'department_id' => '2'],
            [ 'description' => 'BETULIA', 'department_id' => '2'],
            [ 'description' => 'BOLIVAR', 'department_id' => '2'],
            [ 'description' => 'BRICEÑO', 'department_id' => '2'],
            [ 'description' => 'BURITICA', 'department_id' => '2'],
            [ 'description' => 'CACERES', 'department_id' => '2'],
            [ 'description' => 'CAICEDO', 'department_id' => '2'],
            [ 'description' => 'CALDAS', 'department_id' => '2'],
            [ 'description' => 'CAMPAMENTO', 'department_id' => '2'],
            [ 'description' => 'CANASGORDAS', 'department_id' => '2'],
            [ 'description' => 'CARACOLI', 'department_id' => '2'],
            [ 'description' => 'CARAMANTA', 'department_id' => '2'],
            [ 'description' => 'CAREPA', 'department_id' => '2'],
            [ 'description' => 'CARMEN DE VIBORAL', 'department_id' => '2'],
            [ 'description' => 'CAROLINA DEL PRINCIPE', 'department_id' => '2'],
            [ 'description' => 'CAUCASIA', 'department_id' => '2'],
            [ 'description' => 'CHIGORODO', 'department_id' => '2'],
            [ 'description' => 'CISNEROS', 'department_id' => '2'],
            [ 'description' => 'COCORNA', 'department_id' => '2'],
            [ 'description' => 'CONCEPCION', 'department_id' => '2'],
            [ 'description' => 'CONCORDIA', 'department_id' => '2'],
            [ 'description' => 'COPACABANA', 'department_id' => '2'],
            [ 'description' => 'DABEIBA', 'department_id' => '2'],
            [ 'description' => 'DONMATIAS', 'department_id' => '2'],
            [ 'description' => 'EBEJICO', 'department_id' => '2'],
            [ 'description' => 'EL BAGRE', 'department_id' => '2'],
            [ 'description' => 'EL PENOL', 'department_id' => '2'],
            [ 'description' => 'EL RETIRO', 'department_id' => '2'],
            [ 'description' => 'ENTRERRIOS', 'department_id' => '2'],
            [ 'description' => 'ENVIGADO', 'department_id' => '2'],
            [ 'description' => 'FREDONIA', 'department_id' => '2'],
            [ 'description' => 'FRONTINO', 'department_id' => '2'],
            [ 'description' => 'GIRALDO', 'department_id' => '2'],
            [ 'description' => 'GIRARDOTA', 'department_id' => '2'],
            [ 'description' => 'GOMEZ PLATA', 'department_id' => '2'],
            [ 'description' => 'GRANADA', 'department_id' => '2'],
            [ 'description' => 'GUADALUPE', 'department_id' => '2'],
            [ 'description' => 'GUARNE', 'department_id' => '2'],
            [ 'description' => 'GUATAQUE', 'department_id' => '2'],
            [ 'description' => 'HELICONIA', 'department_id' => '2'],
            [ 'description' => 'HISPANIA', 'department_id' => '2'],
            [ 'description' => 'ITAGUI', 'department_id' => '2'],
            [ 'description' => 'ITUANGO', 'department_id' => '2'],
            [ 'description' => 'JARDIN', 'department_id' => '2'],
            [ 'description' => 'JERICO', 'department_id' => '2'],
            [ 'description' => 'LA CEJA', 'department_id' => '2'],
            [ 'description' => 'LA ESTRELLA', 'department_id' => '2'],
            [ 'description' => 'LA PINTADA', 'department_id' => '2'],
            [ 'description' => 'LA UNION', 'department_id' => '2'],
            [ 'description' => 'LIBORINA', 'department_id' => '2'],
            [ 'description' => 'MACEO', 'department_id' => '2'],
            [ 'description' => 'MARINILLA', 'department_id' => '2'],
            [ 'description' => 'MEDELLIN', 'department_id' => '2'],
            [ 'description' => 'MONTEBELLO', 'department_id' => '2'],
            [ 'description' => 'MURINDO', 'department_id' => '2'],
            [ 'description' => 'MUTATA', 'department_id' => '2'],
            [ 'description' => 'NARINO', 'department_id' => '2'],
            [ 'description' => 'NECHI', 'department_id' => '2'],
            [ 'description' => 'NECOCLI', 'department_id' => '2'],
            [ 'description' => 'OLAYA', 'department_id' => '2'],
            [ 'description' => 'PEQUE', 'department_id' => '2'],
            [ 'description' => 'PUEBLORRICO', 'department_id' => '2'],
            [ 'description' => 'PUERTO BERRIO', 'department_id' => '2'],
            [ 'description' => 'PUERTO NARE', 'department_id' => '2'],
            [ 'description' => 'PUERTO TRIUNFO', 'department_id' => '2'],
            [ 'description' => 'REMEDIOS', 'department_id' => '2'],
            [ 'description' => 'RIONEGRO', 'department_id' => '2'],
            [ 'description' => 'SABANALARGA', 'department_id' => '2'],
            [ 'description' => 'SABANETA', 'department_id' => '2'],
            [ 'description' => 'SALGAR', 'department_id' => '2'],
            [ 'description' => 'SAN ANDRES DE CUERQUIA', 'department_id' => '2'],
            [ 'description' => 'SAN CARLOS', 'department_id' => '2'],
            [ 'description' => 'SAN FRANCISCO', 'department_id' => '2'],
            [ 'description' => 'SAN JERONIMO', 'department_id' => '2'],
            [ 'description' => 'SAN JOSE DE LA MONTAÑA', 'department_id' => '2'],
            [ 'description' => 'SAN JUAN DE URABA', 'department_id' => '2'],
            [ 'description' => 'SAN LUIS', 'department_id' => '2'],
            [ 'description' => 'SAN PEDRO DE LOS MILAGROS', 'department_id' => '2'],
            [ 'description' => 'SAN PEDRO DE URABA', 'department_id' => '2'],
            [ 'description' => 'SAN RAFAEL', 'department_id' => '2'],
            [ 'description' => 'SAN ROQUE', 'department_id' => '2'],
            [ 'description' => 'SAN VICENTE', 'department_id' => '2'],
            [ 'description' => 'SANTA BARBARA', 'department_id' => '2'],
            [ 'description' => 'SANTA ROSA DE OSOS', 'department_id' => '2'],
            [ 'description' => 'SANTO DOMINGO', 'department_id' => '2'],
            [ 'description' => 'SANTUARIO', 'department_id' => '2'],
            [ 'description' => 'SEGOVIA', 'department_id' => '2'],
            [ 'description' => 'SONSON', 'department_id' => '2'],
            [ 'description' => 'SOPETRAN', 'department_id' => '2'],
            [ 'description' => 'TAMESIS', 'department_id' => '2'],
            [ 'description' => 'TARAZA', 'department_id' => '2'],
            [ 'description' => 'TARSO', 'department_id' => '2'],
            [ 'description' => 'TITIRIBI', 'department_id' => '2'],
            [ 'description' => 'TOLEDO', 'department_id' => '2'],
            [ 'description' => 'TURBO', 'department_id' => '2'],
            [ 'description' => 'URAMITA', 'department_id' => '2'],
            [ 'description' => 'URRAO', 'department_id' => '2'],
            [ 'description' => 'VALDIVIA', 'department_id' => '2'],
            [ 'description' => 'VALPARAISO', 'department_id' => '2'],
            [ 'description' => 'VEGACHI', 'department_id' => '2'],
            [ 'description' => 'VENECIA', 'department_id' => '2'],
            [ 'description' => 'VIGIA DEL FUERTE', 'department_id' => '2'],
            [ 'description' => 'YALI', 'department_id' => '2'],
            [ 'description' => 'YARUMAL', 'department_id' => '2'],
            [ 'description' => 'YOLOMBO', 'department_id' => '2'],
            [ 'description' => 'YONDO', 'department_id' => '2'],
            [ 'description' => 'ZARAGOZA', 'department_id' => '2'],
            [ 'description' => 'ARAUCA', 'department_id' => '3'],
            [ 'description' => 'ARAUQUITA', 'department_id' => '3'],
            [ 'description' => 'CRAVO NORTE', 'department_id' => '3'],
            [ 'description' => 'FORTUL', 'department_id' => '3'],
            [ 'description' => 'PUERTO RONDON', 'department_id' => '3'],
            [ 'description' => 'SARAVENA', 'department_id' => '3'],
            [ 'description' => 'TAME', 'department_id' => '3'],
            [ 'description' => 'BARANOA', 'department_id' => '4'],
            [ 'description' => 'BARRANQUILLA', 'department_id' => '4'],
            [ 'description' => 'CAMPO DE LA CRUZ', 'department_id' => '4'],
            [ 'description' => 'CANDELARIA', 'department_id' => '4'],
            [ 'description' => 'GALAPA', 'department_id' => '4'],
            [ 'description' => 'JUAN DE ACOSTA', 'department_id' => '4'],
            [ 'description' => 'LURUACO', 'department_id' => '4'],
            [ 'description' => 'MALAMBO', 'department_id' => '4'],
            [ 'description' => 'MANATI', 'department_id' => '4'],
            [ 'description' => 'PALMAR DE VARELA', 'department_id' => '4'],
            [ 'description' => 'PIOJO', 'department_id' => '4'],
            [ 'description' => 'POLO NUEVO', 'department_id' => '4'],
            [ 'description' => 'PONEDERA', 'department_id' => '4'],
            [ 'description' => 'PUERTO COLOMBIA', 'department_id' => '4'],
            [ 'description' => 'REPELON', 'department_id' => '4'],
            [ 'description' => 'SABANAGRANDE', 'department_id' => '4'],
            [ 'description' => 'SABANALARGA', 'department_id' => '4'],
            [ 'description' => 'SANTA LUCIA', 'department_id' => '4'],
            [ 'description' => 'SANTO TOMAS', 'department_id' => '4'],
            [ 'description' => 'SOLEDAD', 'department_id' => '4'],
            [ 'description' => 'SUAN', 'department_id' => '4'],
            [ 'description' => 'TUBARA', 'department_id' => '4'],
            [ 'description' => 'USIACURI', 'department_id' => '4'],
            [ 'description' => 'ACHI', 'department_id' => '5'],
            [ 'description' => 'ALTOS DEL ROSARIO', 'department_id' => '5'],
            [ 'description' => 'ARENAL', 'department_id' => '5'],
            [ 'description' => 'ARJONA', 'department_id' => '5'],
            [ 'description' => 'ARROYOHONDO', 'department_id' => '5'],
            [ 'description' => 'BARRANCO DE LOBA', 'department_id' => '5'],
            [ 'description' => 'BRAZUELO DE PAPAYAL', 'department_id' => '5'],
            [ 'description' => 'CALAMAR', 'department_id' => '5'],
            [ 'description' => 'CANTAGALLO', 'department_id' => '5'],
            [ 'description' => 'CARTAGENA DE INDIAS', 'department_id' => '5'],
            [ 'description' => 'CICUCO', 'department_id' => '5'],
            [ 'description' => 'CLEMENCIA', 'department_id' => '5'],
            [ 'description' => 'CORDOBA', 'department_id' => '5'],
            [ 'description' => 'EL CARMEN DE BOLIVAR', 'department_id' => '5'],
            [ 'description' => 'EL GUAMO', 'department_id' => '5'],
            [ 'description' => 'EL PENION', 'department_id' => '5'],
            [ 'description' => 'HATILLO DE LOBA', 'department_id' => '5'],
            [ 'description' => 'MAGANGUE', 'department_id' => '5'],
            [ 'description' => 'MAHATES', 'department_id' => '5'],
            [ 'description' => 'MARGARITA', 'department_id' => '5'],
            [ 'description' => 'MARIA LA BAJA', 'department_id' => '5'],
            [ 'description' => 'MONTECRISTO', 'department_id' => '5'],
            [ 'description' => 'MORALES', 'department_id' => '5'],
            [ 'description' => 'MORALES', 'department_id' => '5'],
            [ 'description' => 'NOROSI', 'department_id' => '5'],
            [ 'description' => 'PINILLOS', 'department_id' => '5'],
            [ 'description' => 'REGIDOR', 'department_id' => '5'],
            [ 'description' => 'RIO VIEJO', 'department_id' => '5'],
            [ 'description' => 'SAN CRISTOBAL', 'department_id' => '5'],
            [ 'description' => 'SAN ESTANISLAO', 'department_id' => '5'],
            [ 'description' => 'SAN FERNANDO', 'department_id' => '5'],
            [ 'description' => 'SAN JACINTO', 'department_id' => '5'],
            [ 'description' => 'SAN JACINTO DEL CAUCA', 'department_id' => '5'],
            [ 'description' => 'SAN JUAN DE NEPOMUCENO', 'department_id' => '5'],
            [ 'description' => 'SAN MARTIN DE LOBA', 'department_id' => '5'],
            [ 'description' => 'SAN PABLO', 'department_id' => '5'],
            [ 'description' => 'SAN PABLO NORTE', 'department_id' => '5'],
            [ 'description' => 'SANTA CATALINA', 'department_id' => '5'],
            [ 'description' => 'SANTA CRUZ DE MOMPOX', 'department_id' => '5'],
            [ 'description' => 'SANTA ROSA', 'department_id' => '5'],
            [ 'description' => 'SANTA ROSA DEL SUR', 'department_id' => '5'],
            [ 'description' => 'SIMITI', 'department_id' => '5'],
            [ 'description' => 'SOPLAVIENTO', 'department_id' => '5'],
            [ 'description' => 'TALAIGUA NUEVO', 'department_id' => '5'],
            [ 'description' => 'TUQUISIO', 'department_id' => '5'],
            [ 'description' => 'TURBACO', 'department_id' => '5'],
            [ 'description' => 'TURBANA', 'department_id' => '5'],
            [ 'description' => 'VILLANUEVA', 'department_id' => '5'],
            [ 'description' => 'ZAMBRANO', 'department_id' => '5'],
            [ 'description' => 'AQUITANIA', 'department_id' => '6'],
            [ 'description' => 'ARCABUCO', 'department_id' => '6'],
            [ 'description' => 'BELÉN', 'department_id' => '6'],
            [ 'description' => 'BERBEO', 'department_id' => '6'],
            [ 'description' => 'BETÉITIVA', 'department_id' => '6'],
            [ 'description' => 'BOAVITA', 'department_id' => '6'],
            [ 'description' => 'BOYACÁ', 'department_id' => '6'],
            [ 'description' => 'BRICEÑO', 'department_id' => '6'],
            [ 'description' => 'BUENAVISTA', 'department_id' => '6'],
            [ 'description' => 'BUSBANZÁ', 'department_id' => '6'],
            [ 'description' => 'CALDAS', 'department_id' => '6'],
            [ 'description' => 'CAMPO HERMOSO', 'department_id' => '6'],
            [ 'description' => 'CERINZA', 'department_id' => '6'],
            [ 'description' => 'CHINAVITA', 'department_id' => '6'],
            [ 'description' => 'CHIQUINQUIRÁ', 'department_id' => '6'],
            [ 'description' => 'CHÍQUIZA', 'department_id' => '6'],
            [ 'description' => 'CHISCAS', 'department_id' => '6'],
            [ 'description' => 'CHITA', 'department_id' => '6'],
            [ 'description' => 'CHITARAQUE', 'department_id' => '6'],
            [ 'description' => 'CHIVATÁ', 'department_id' => '6'],
            [ 'description' => 'CIÉNEGA', 'department_id' => '6'],
            [ 'description' => 'CÓMBITA', 'department_id' => '6'],
            [ 'description' => 'COPER', 'department_id' => '6'],
            [ 'description' => 'CORRALES', 'department_id' => '6'],
            [ 'description' => 'COVARACHÍA', 'department_id' => '6'],
            [ 'description' => 'CUBARA', 'department_id' => '6'],
            [ 'description' => 'CUCAITA', 'department_id' => '6'],
            [ 'description' => 'CUITIVA', 'department_id' => '6'],
            [ 'description' => 'DUITAMA', 'department_id' => '6'],
            [ 'description' => 'EL COCUY', 'department_id' => '6'],
            [ 'description' => 'EL ESPINO', 'department_id' => '6'],
            [ 'description' => 'FIRAVITOBA', 'department_id' => '6'],
            [ 'description' => 'FLORESTA', 'department_id' => '6'],
            [ 'description' => 'GACHANTIVÁ', 'department_id' => '6'],
            [ 'description' => 'GÁMEZA', 'department_id' => '6'],
            [ 'description' => 'GARAGOA', 'department_id' => '6'],
            [ 'description' => 'GUACAMAYAS', 'department_id' => '6'],
            [ 'description' => 'GÜICÁN', 'department_id' => '6'],
            [ 'description' => 'IZA', 'department_id' => '6'],
            [ 'description' => 'JENESANO', 'department_id' => '6'],
            [ 'description' => 'JERICÓ', 'department_id' => '6'],
            [ 'description' => 'LA UVITA', 'department_id' => '6'],
            [ 'description' => 'LA VICTORIA', 'department_id' => '6'],
            [ 'description' => 'LABRANZA GRANDE', 'department_id' => '6'],
            [ 'description' => 'MACANAL', 'department_id' => '6'],
            [ 'description' => 'MARIPÍ', 'department_id' => '6'],
            [ 'description' => 'MIRAFLORES', 'department_id' => '6'],
            [ 'description' => 'MONGUA', 'department_id' => '6'],
            [ 'description' => 'MONGUÍ', 'department_id' => '6'],
            [ 'description' => 'MONIQUIRÁ', 'department_id' => '6'],
            [ 'description' => 'MOTAVITA', 'department_id' => '6'],
            [ 'description' => 'MUZO', 'department_id' => '6'],
            [ 'description' => 'NOBSA', 'department_id' => '6'],
            [ 'description' => 'NUEVO COLÓN', 'department_id' => '6'],
            [ 'description' => 'OICATÁ', 'department_id' => '6'],
            [ 'description' => 'OTANCHE', 'department_id' => '6'],
            [ 'description' => 'PACHAVITA', 'department_id' => '6'],
            [ 'description' => 'PÁEZ', 'department_id' => '6'],
            [ 'description' => 'PAIPA', 'department_id' => '6'],
            [ 'description' => 'PAJARITO', 'department_id' => '6'],
            [ 'description' => 'PANQUEBA', 'department_id' => '6'],
            [ 'description' => 'PAUNA', 'department_id' => '6'],
            [ 'description' => 'PAYA', 'department_id' => '6'],
            [ 'description' => 'PAZ DE RÍO', 'department_id' => '6'],
            [ 'description' => 'PESCA', 'department_id' => '6'],
            [ 'description' => 'PISBA', 'department_id' => '6'],
            [ 'description' => 'PUERTO BOYACA', 'department_id' => '6'],
            [ 'description' => 'QUÍPAMA', 'department_id' => '6'],
            [ 'description' => 'RAMIRIQUÍ', 'department_id' => '6'],
            [ 'description' => 'RÁQUIRA', 'department_id' => '6'],
            [ 'description' => 'RONDÓN', 'department_id' => '6'],
            [ 'description' => 'SABOYÁ', 'department_id' => '6'],
            [ 'description' => 'SÁCHICA', 'department_id' => '6'],
            [ 'description' => 'SAMACÁ', 'department_id' => '6'],
            [ 'description' => 'SAN EDUARDO', 'department_id' => '6'],
            [ 'description' => 'SAN JOSÉ DE PARE', 'department_id' => '6'],
            [ 'description' => 'SAN LUÍS DE GACENO', 'department_id' => '6'],
            [ 'description' => 'SAN MATEO', 'department_id' => '6'],
            [ 'description' => 'SAN MIGUEL DE SEMA', 'department_id' => '6'],
            [ 'description' => 'SAN PABLO DE BORBUR', 'department_id' => '6'],
            [ 'description' => 'SANTA MARÍA', 'department_id' => '6'],
            [ 'description' => 'SANTA ROSA DE VITERBO', 'department_id' => '6'],
            [ 'description' => 'SANTA SOFÍA', 'department_id' => '6'],
            [ 'description' => 'SANTANA', 'department_id' => '6'],
            [ 'description' => 'SATIVANORTE', 'department_id' => '6'],
            [ 'description' => 'SATIVASUR', 'department_id' => '6'],
            [ 'description' => 'SIACHOQUE', 'department_id' => '6'],
            [ 'description' => 'SOATÁ', 'department_id' => '6'],
            [ 'description' => 'SOCHA', 'department_id' => '6'],
            [ 'description' => 'SOCOTÁ', 'department_id' => '6'],
            [ 'description' => 'SOGAMOSO', 'department_id' => '6'],
            [ 'description' => 'SORA', 'department_id' => '6'],
            [ 'description' => 'SORACÁ', 'department_id' => '6'],
            [ 'description' => 'SOTAQUIRÁ', 'department_id' => '6'],
            [ 'description' => 'SUSACÓN', 'department_id' => '6'],
            [ 'description' => 'SUTARMACHÁN', 'department_id' => '6'],
            [ 'description' => 'TASCO', 'department_id' => '6'],
            [ 'description' => 'TIBANÁ', 'department_id' => '6'],
            [ 'description' => 'TIBASOSA', 'department_id' => '6'],
            [ 'description' => 'TINJACÁ', 'department_id' => '6'],
            [ 'description' => 'TIPACOQUE', 'department_id' => '6'],
            [ 'description' => 'TOCA', 'department_id' => '6'],
            [ 'description' => 'TOGÜÍ', 'department_id' => '6'],
            [ 'description' => 'TÓPAGA', 'department_id' => '6'],
            [ 'description' => 'TOTA', 'department_id' => '6'],
            [ 'description' => 'TUNJA', 'department_id' => '6'],
            [ 'description' => 'TUNUNGUÁ', 'department_id' => '6'],
            [ 'description' => 'TURMEQUÉ', 'department_id' => '6'],
            [ 'description' => 'TUTA', 'department_id' => '6'],
            [ 'description' => 'TUTAZÁ', 'department_id' => '6'],
            [ 'description' => 'UMBITA', 'department_id' => '6'],
            [ 'description' => 'VENTA QUEMADA', 'department_id' => '6'],
            [ 'description' => 'VILLA DE LEYVA', 'department_id' => '6'],
            [ 'description' => 'VIRACACHÁ', 'department_id' => '6'],
            [ 'description' => 'ZETAQUIRA', 'department_id' => '6'],
            [ 'description' => 'AGUADAS', 'department_id' => '7'],
            [ 'description' => 'ANSERMA', 'department_id' => '7'],
            [ 'description' => 'ARANZAZU', 'department_id' => '7'],
            [ 'description' => 'BELALCAZAR', 'department_id' => '7'],
            [ 'description' => 'CHINCHINÁ', 'department_id' => '7'],
            [ 'description' => 'FILADELFIA', 'department_id' => '7'],
            [ 'description' => 'LA DORADA', 'department_id' => '7'],
            [ 'description' => 'LA MERCED', 'department_id' => '7'],
            [ 'description' => 'MANIZALES', 'department_id' => '7'],
            [ 'description' => 'MANZANARES', 'department_id' => '7'],
            [ 'description' => 'MARMATO', 'department_id' => '7'],
            [ 'description' => 'MARQUETALIA', 'department_id' => '7'],
            [ 'description' => 'MARULANDA', 'department_id' => '7'],
            [ 'description' => 'NEIRA', 'department_id' => '7'],
            [ 'description' => 'NORCASIA', 'department_id' => '7'],
            [ 'description' => 'PACORA', 'department_id' => '7'],
            [ 'description' => 'PALESTINA', 'department_id' => '7'],
            [ 'description' => 'PENSILVANIA', 'department_id' => '7'],
            [ 'description' => 'RIOSUCIO', 'department_id' => '7'],
            [ 'description' => 'RISARALDA', 'department_id' => '7'],
            [ 'description' => 'SALAMINA', 'department_id' => '7'],
            [ 'description' => 'SAMANA', 'department_id' => '7'],
            [ 'description' => 'SAN JOSE', 'department_id' => '7'],
            [ 'description' => 'SUPÍA', 'department_id' => '7'],
            [ 'description' => 'VICTORIA', 'department_id' => '7'],
            [ 'description' => 'VILLAMARÍA', 'department_id' => '7'],
            [ 'description' => 'VITERBO', 'department_id' => '7'],
            [ 'description' => 'ALBANIA', 'department_id' => '8'],
            [ 'description' => 'BELÉN ANDAQUIES', 'department_id' => '8'],
            [ 'description' => 'CARTAGENA DEL CHAIRA', 'department_id' => '8'],
            [ 'description' => 'CURILLO', 'department_id' => '8'],
            [ 'description' => 'EL DONCELLO', 'department_id' => '8'],
            [ 'description' => 'EL PAUJIL', 'department_id' => '8'],
            [ 'description' => 'FLORENCIA', 'department_id' => '8'],
            [ 'description' => 'LA MONTAÑITA', 'department_id' => '8'],
            [ 'description' => 'MILÁN', 'department_id' => '8'],
            [ 'description' => 'MORELIA', 'department_id' => '8'],
            [ 'description' => 'PUERTO RICO', 'department_id' => '8'],
            [ 'description' => 'SAN  VICENTE DEL CAGUAN', 'department_id' => '8'],
            [ 'description' => 'SAN JOSÉ DE FRAGUA', 'department_id' => '8'],
            [ 'description' => 'SOLANO', 'department_id' => '8'],
            [ 'description' => 'SOLITA', 'department_id' => '8'],
            [ 'description' => 'VALPARAÍSO', 'department_id' => '8'],
            [ 'description' => 'AGUAZUL', 'department_id' => '9'],
            [ 'description' => 'CHAMEZA', 'department_id' => '9'],
            [ 'description' => 'HATO COROZAL', 'department_id' => '9'],
            [ 'description' => 'LA SALINA', 'department_id' => '9'],
            [ 'description' => 'MANÍ', 'department_id' => '9'],
            [ 'description' => 'MONTERREY', 'department_id' => '9'],
            [ 'description' => 'NUNCHIA', 'department_id' => '9'],
            [ 'description' => 'OROCUE', 'department_id' => '9'],
            [ 'description' => 'PAZ DE ARIPORO', 'department_id' => '9'],
            [ 'description' => 'PORE', 'department_id' => '9'],
            [ 'description' => 'RECETOR', 'department_id' => '9'],
            [ 'description' => 'SABANA LARGA', 'department_id' => '9'],
            [ 'description' => 'SACAMA', 'department_id' => '9'],
            [ 'description' => 'SAN LUIS DE PALENQUE', 'department_id' => '9'],
            [ 'description' => 'TAMARA', 'department_id' => '9'],
            [ 'description' => 'TAURAMENA', 'department_id' => '9'],
            [ 'description' => 'TRINIDAD', 'department_id' => '9'],
            [ 'description' => 'VILLANUEVA', 'department_id' => '9'],
            [ 'description' => 'YOPAL', 'department_id' => '9'],
            [ 'description' => 'ALMAGUER', 'department_id' => '10'],
            [ 'description' => 'ARGELIA', 'department_id' => '10'],
            [ 'description' => 'BALBOA', 'department_id' => '10'],
            [ 'description' => 'BOLÍVAR', 'department_id' => '10'],
            [ 'description' => 'BUENOS AIRES', 'department_id' => '10'],
            [ 'description' => 'CAJIBIO', 'department_id' => '10'],
            [ 'description' => 'CALDONO', 'department_id' => '10'],
            [ 'description' => 'CALOTO', 'department_id' => '10'],
            [ 'description' => 'CORINTO', 'department_id' => '10'],
            [ 'description' => 'EL TAMBO', 'department_id' => '10'],
            [ 'description' => 'FLORENCIA', 'department_id' => '10'],
            [ 'description' => 'GUAPI', 'department_id' => '10'],
            [ 'description' => 'INZA', 'department_id' => '10'],
            [ 'description' => 'JAMBALÓ', 'department_id' => '10'],
            [ 'description' => 'LA SIERRA', 'department_id' => '10'],
            [ 'description' => 'LA VEGA', 'department_id' => '10'],
            [ 'description' => 'LÓPEZ', 'department_id' => '10'],
            [ 'description' => 'MERCADERES', 'department_id' => '10'],
            [ 'description' => 'MIRANDA', 'department_id' => '10'],
            [ 'description' => 'MORALES', 'department_id' => '10'],
            [ 'description' => 'PADILLA', 'department_id' => '10'],
            [ 'description' => 'PÁEZ', 'department_id' => '10'],
            [ 'description' => 'PATIA (EL BORDO)', 'department_id' => '10'],
            [ 'description' => 'PIAMONTE', 'department_id' => '10'],
            [ 'description' => 'PIENDAMO', 'department_id' => '10'],
            [ 'description' => 'POPAYÁN', 'department_id' => '10'],
            [ 'description' => 'PUERTO TEJADA', 'department_id' => '10'],
            [ 'description' => 'PURACE', 'department_id' => '10'],
            [ 'description' => 'ROSAS', 'department_id' => '10'],
            [ 'description' => 'SAN SEBASTIÁN', 'department_id' => '10'],
            [ 'description' => 'SANTA ROSA', 'department_id' => '10'],
            [ 'description' => 'SANTANDER DE QUILICHAO', 'department_id' => '10'],
            [ 'description' => 'SILVIA', 'department_id' => '10'],
            [ 'description' => 'SOTARA', 'department_id' => '10'],
            [ 'description' => 'SUÁREZ', 'department_id' => '10'],
            [ 'description' => 'SUCRE', 'department_id' => '10'],
            [ 'description' => 'TIMBÍO', 'department_id' => '10'],
            [ 'description' => 'TIMBIQUÍ', 'department_id' => '10'],
            [ 'description' => 'TORIBIO', 'department_id' => '10'],
            [ 'description' => 'TOTORO', 'department_id' => '10'],
            [ 'description' => 'VILLA RICA', 'department_id' => '10'],
            [ 'description' => 'AGUACHICA', 'department_id' => '11'],
            [ 'description' => 'AGUSTÍN CODAZZI', 'department_id' => '11'],
            [ 'description' => 'ASTREA', 'department_id' => '11'],
            [ 'description' => 'BECERRIL', 'department_id' => '11'],
            [ 'description' => 'BOSCONIA', 'department_id' => '11'],
            [ 'description' => 'CHIMICHAGUA', 'department_id' => '11'],
            [ 'description' => 'CHIRIGUANÁ', 'department_id' => '11'],
            [ 'description' => 'CURUMANÍ', 'department_id' => '11'],
            [ 'description' => 'EL COPEY', 'department_id' => '11'],
            [ 'description' => 'EL PASO', 'department_id' => '11'],
            [ 'description' => 'GAMARRA', 'department_id' => '11'],
            [ 'description' => 'GONZÁLEZ', 'department_id' => '11'],
            [ 'description' => 'LA GLORIA', 'department_id' => '11'],
            [ 'description' => 'LA JAGUA IBIRICO', 'department_id' => '11'],
            [ 'description' => 'MANAURE BALCÓN DEL CESAR', 'department_id' => '11'],
            [ 'description' => 'PAILITAS', 'department_id' => '11'],
            [ 'description' => 'PELAYA', 'department_id' => '11'],
            [ 'description' => 'PUEBLO BELLO', 'department_id' => '11'],
            [ 'description' => 'RÍO DE ORO', 'department_id' => '11'],
            [ 'description' => 'ROBLES (LA PAZ)', 'department_id' => '11'],
            [ 'description' => 'SAN ALBERTO', 'department_id' => '11'],
            [ 'description' => 'SAN DIEGO', 'department_id' => '11'],
            [ 'description' => 'SAN MARTÍN', 'department_id' => '11'],
            [ 'description' => 'TAMALAMEQUE', 'department_id' => '11'],
            [ 'description' => 'VALLEDUPAR', 'department_id' => '11'],
            [ 'description' => 'ACANDI', 'department_id' => '12'],
            [ 'description' => 'ALTO BAUDO (PIE DE PATO)', 'department_id' => '12'],
            [ 'description' => 'ATRATO', 'department_id' => '12'],
            [ 'description' => 'BAGADO', 'department_id' => '12'],
            [ 'description' => 'BAHIA SOLANO (MUTIS)', 'department_id' => '12'],
            [ 'description' => 'BAJO BAUDO (PIZARRO)', 'department_id' => '12'],
            [ 'description' => 'BOJAYA (BELLAVISTA)', 'department_id' => '12'],
            [ 'description' => 'CANTON DE SAN PABLO', 'department_id' => '12'],
            [ 'description' => 'CARMEN DEL DARIEN', 'department_id' => '12'],
            [ 'description' => 'CERTEGUI', 'department_id' => '12'],
            [ 'description' => 'CONDOTO', 'department_id' => '12'],
            [ 'description' => 'EL CARMEN', 'department_id' => '12'],
            [ 'description' => 'ISTMINA', 'department_id' => '12'],
            [ 'description' => 'JURADO', 'department_id' => '12'],
            [ 'description' => 'LITORAL DEL SAN JUAN', 'department_id' => '12'],
            [ 'description' => 'LLORO', 'department_id' => '12'],
            [ 'description' => 'MEDIO ATRATO', 'department_id' => '12'],
            [ 'description' => 'MEDIO BAUDO (BOCA DE PEPE)', 'department_id' => '12'],
            [ 'description' => 'MEDIO SAN JUAN', 'department_id' => '12'],
            [ 'description' => 'NOVITA', 'department_id' => '12'],
            [ 'description' => 'NUQUI', 'department_id' => '12'],
            [ 'description' => 'QUIBDO', 'department_id' => '12'],
            [ 'description' => 'RIO IRO', 'department_id' => '12'],
            [ 'description' => 'RIO QUITO', 'department_id' => '12'],
            [ 'description' => 'RIOSUCIO', 'department_id' => '12'],
            [ 'description' => 'SAN JOSE DEL PALMAR', 'department_id' => '12'],
            [ 'description' => 'SIPI', 'department_id' => '12'],
            [ 'description' => 'TADO', 'department_id' => '12'],
            [ 'description' => 'UNGUIA', 'department_id' => '12'],
            [ 'description' => 'UNIÓN PANAMERICANA', 'department_id' => '12'],
            [ 'description' => 'AYAPEL', 'department_id' => '13'],
            [ 'description' => 'BUENAVISTA', 'department_id' => '13'],
            [ 'description' => 'CANALETE', 'department_id' => '13'],
            [ 'description' => 'CERETÉ', 'department_id' => '13'],
            [ 'description' => 'CHIMA', 'department_id' => '13'],
            [ 'description' => 'CHINÚ', 'department_id' => '13'],
            [ 'description' => 'CIENAGA DE ORO', 'department_id' => '13'],
            [ 'description' => 'COTORRA', 'department_id' => '13'],
            [ 'description' => 'LA APARTADA', 'department_id' => '13'],
            [ 'description' => 'LORICA', 'department_id' => '13'],
            [ 'description' => 'LOS CÓRDOBAS', 'department_id' => '13'],
            [ 'description' => 'MOMIL', 'department_id' => '13'],
            [ 'description' => 'MONTELÍBANO', 'department_id' => '13'],
            [ 'description' => 'MONTERÍA', 'department_id' => '13'],
            [ 'description' => 'MOÑITOS', 'department_id' => '13'],
            [ 'description' => 'PLANETA RICA', 'department_id' => '13'],
            [ 'description' => 'PUEBLO NUEVO', 'department_id' => '13'],
            [ 'description' => 'PUERTO ESCONDIDO', 'department_id' => '13'],
            [ 'description' => 'PUERTO LIBERTADOR', 'department_id' => '13'],
            [ 'description' => 'PURÍSIMA', 'department_id' => '13'],
            [ 'description' => 'SAHAGÚN', 'department_id' => '13'],
            [ 'description' => 'SAN ANDRÉS SOTAVENTO', 'department_id' => '13'],
            [ 'description' => 'SAN ANTERO', 'department_id' => '13'],
            [ 'description' => 'SAN BERNARDO VIENTO', 'department_id' => '13'],
            [ 'description' => 'SAN CARLOS', 'department_id' => '13'],
            [ 'description' => 'SAN PELAYO', 'department_id' => '13'],
            [ 'description' => 'TIERRALTA', 'department_id' => '13'],
            [ 'description' => 'VALENCIA', 'department_id' => '13'],
            [ 'description' => 'AGUA DE DIOS', 'department_id' => '14'],
            [ 'description' => 'ALBAN', 'department_id' => '14'],
            [ 'description' => 'ANAPOIMA', 'department_id' => '14'],
            [ 'description' => 'ANOLAIMA', 'department_id' => '14'],
            [ 'description' => 'ARBELAEZ', 'department_id' => '14'],
            [ 'description' => 'BELTRÁN', 'department_id' => '14'],
            [ 'description' => 'BITUIMA', 'department_id' => '14'],
            [ 'description' => 'BOGOTÁ DC', 'department_id' => '14'],
            [ 'description' => 'BOJACÁ', 'department_id' => '14'],
            [ 'description' => 'CABRERA', 'department_id' => '14'],
            [ 'description' => 'CACHIPAY', 'department_id' => '14'],
            [ 'description' => 'CAJICÁ', 'department_id' => '14'],
            [ 'description' => 'CAPARRAPÍ', 'department_id' => '14'],
            [ 'description' => 'CAQUEZA', 'department_id' => '14'],
            [ 'description' => 'CARMEN DE CARUPA', 'department_id' => '14'],
            [ 'description' => 'CHAGUANÍ', 'department_id' => '14'],
            [ 'description' => 'CHIA', 'department_id' => '14'],
            [ 'description' => 'CHIPAQUE', 'department_id' => '14'],
            [ 'description' => 'CHOACHÍ', 'department_id' => '14'],
            [ 'description' => 'CHOCONTÁ', 'department_id' => '14'],
            [ 'description' => 'COGUA', 'department_id' => '14'],
            [ 'description' => 'COTA', 'department_id' => '14'],
            [ 'description' => 'CUCUNUBÁ', 'department_id' => '14'],
            [ 'description' => 'EL COLEGIO', 'department_id' => '14'],
            [ 'description' => 'EL PEÑÓN', 'department_id' => '14'],
            [ 'description' => 'EL ROSAL1', 'department_id' => '14'],
            [ 'description' => 'FACATATIVA', 'department_id' => '14'],
            [ 'description' => 'FÓMEQUE', 'department_id' => '14'],
            [ 'description' => 'FOSCA', 'department_id' => '14'],
            [ 'description' => 'FUNZA', 'department_id' => '14'],
            [ 'description' => 'FÚQUENE', 'department_id' => '14'],
            [ 'description' => 'FUSAGASUGA', 'department_id' => '14'],
            [ 'description' => 'GACHALÁ', 'department_id' => '14'],
            [ 'description' => 'GACHANCIPÁ', 'department_id' => '14'],
            [ 'description' => 'GACHETA', 'department_id' => '14'],
            [ 'description' => 'GAMA', 'department_id' => '14'],
            [ 'description' => 'GIRARDOT', 'department_id' => '14'],
            [ 'description' => 'GRANADA2', 'department_id' => '14'],
            [ 'description' => 'GUACHETÁ', 'department_id' => '14'],
            [ 'description' => 'GUADUAS', 'department_id' => '14'],
            [ 'description' => 'GUASCA', 'department_id' => '14'],
            [ 'description' => 'GUATAQUÍ', 'department_id' => '14'],
            [ 'description' => 'GUATAVITA', 'department_id' => '14'],
            [ 'description' => 'GUAYABAL DE SIQUIMA', 'department_id' => '14'],
            [ 'description' => 'GUAYABETAL', 'department_id' => '14'],
            [ 'description' => 'GUTIÉRREZ', 'department_id' => '14'],
            [ 'description' => 'JERUSALÉN', 'department_id' => '14'],
            [ 'description' => 'JUNÍN', 'department_id' => '14'],
            [ 'description' => 'LA CALERA', 'department_id' => '14'],
            [ 'description' => 'LA MESA', 'department_id' => '14'],
            [ 'description' => 'LA PALMA', 'department_id' => '14'],
            [ 'description' => 'LA PEÑA', 'department_id' => '14'],
            [ 'description' => 'LA VEGA', 'department_id' => '14'],
            [ 'description' => 'LENGUAZAQUE', 'department_id' => '14'],
            [ 'description' => 'MACHETÁ', 'department_id' => '14'],
            [ 'description' => 'MADRID', 'department_id' => '14'],
            [ 'description' => 'MANTA', 'department_id' => '14'],
            [ 'description' => 'MEDINA', 'department_id' => '14'],
            [ 'description' => 'MOSQUERA', 'department_id' => '14'],
            [ 'description' => 'NARIÑO', 'department_id' => '14'],
            [ 'description' => 'NEMOCÓN', 'department_id' => '14'],
            [ 'description' => 'NILO', 'department_id' => '14'],
            [ 'description' => 'NIMAIMA', 'department_id' => '14'],
            [ 'description' => 'NOCAIMA', 'department_id' => '14'],
            [ 'description' => 'OSPINA PÉREZ', 'department_id' => '14'],
            [ 'description' => 'PACHO', 'department_id' => '14'],
            [ 'description' => 'PAIME', 'department_id' => '14'],
            [ 'description' => 'PANDI', 'department_id' => '14'],
            [ 'description' => 'PARATEBUENO', 'department_id' => '14'],
            [ 'description' => 'PASCA', 'department_id' => '14'],
            [ 'description' => 'PUERTO SALGAR', 'department_id' => '14'],
            [ 'description' => 'PULÍ', 'department_id' => '14'],
            [ 'description' => 'QUEBRADANEGRA', 'department_id' => '14'],
            [ 'description' => 'QUETAME', 'department_id' => '14'],
            [ 'description' => 'QUIPILE', 'department_id' => '14'],
            [ 'description' => 'RAFAEL REYES', 'department_id' => '14'],
            [ 'description' => 'RICAURTE', 'department_id' => '14'],
            [ 'description' => 'SAN  ANTONIO DEL  TEQUENDAMA', 'department_id' => '14'],
            [ 'description' => 'SAN BERNARDO', 'department_id' => '14'],
            [ 'description' => 'SAN CAYETANO', 'department_id' => '14'],
            [ 'description' => 'SAN FRANCISCO', 'department_id' => '14'],
            [ 'description' => 'SAN JUAN DE RIOSECO', 'department_id' => '14'],
            [ 'description' => 'SASAIMA', 'department_id' => '14'],
            [ 'description' => 'SESQUILÉ', 'department_id' => '14'],
            [ 'description' => 'SIBATÉ', 'department_id' => '14'],
            [ 'description' => 'SILVANIA', 'department_id' => '14'],
            [ 'description' => 'SIMIJACA', 'department_id' => '14'],
            [ 'description' => 'SOACHA', 'department_id' => '14'],
            [ 'description' => 'SOPO', 'department_id' => '14'],
            [ 'description' => 'SUBACHOQUE', 'department_id' => '14'],
            [ 'description' => 'SUESCA', 'department_id' => '14'],
            [ 'description' => 'SUPATÁ', 'department_id' => '14'],
            [ 'description' => 'SUSA', 'department_id' => '14'],
            [ 'description' => 'SUTATAUSA', 'department_id' => '14'],
            [ 'description' => 'TABIO', 'department_id' => '14'],
            [ 'description' => 'TAUSA', 'department_id' => '14'],
            [ 'description' => 'TENA', 'department_id' => '14'],
            [ 'description' => 'TENJO', 'department_id' => '14'],
            [ 'description' => 'TIBACUY', 'department_id' => '14'],
            [ 'description' => 'TIBIRITA', 'department_id' => '14'],
            [ 'description' => 'TOCAIMA', 'department_id' => '14'],
            [ 'description' => 'TOCANCIPÁ', 'department_id' => '14'],
            [ 'description' => 'TOPAIPÍ', 'department_id' => '14'],
            [ 'description' => 'UBALÁ', 'department_id' => '14'],
            [ 'description' => 'UBAQUE', 'department_id' => '14'],
            [ 'description' => 'UBATÉ', 'department_id' => '14'],
            [ 'description' => 'UNE', 'department_id' => '14'],
            [ 'description' => 'UTICA', 'department_id' => '14'],
            [ 'description' => 'VERGARA', 'department_id' => '14'],
            [ 'description' => 'VIANI', 'department_id' => '14'],
            [ 'description' => 'VILLA GOMEZ', 'department_id' => '14'],
            [ 'description' => 'VILLA PINZÓN', 'department_id' => '14'],
            [ 'description' => 'VILLETA', 'department_id' => '14'],
            [ 'description' => 'VIOTA', 'department_id' => '14'],
            [ 'description' => 'YACOPÍ', 'department_id' => '14'],
            [ 'description' => 'ZIPACÓN', 'department_id' => '14'],
            [ 'description' => 'ZIPAQUIRÁ', 'department_id' => '14'],
            [ 'description' => 'BARRANCO MINAS', 'department_id' => '15'],
            [ 'description' => 'CACAHUAL', 'department_id' => '15'],
            [ 'description' => 'INÍRIDA', 'department_id' => '15'],
            [ 'description' => 'LA GUADALUPE', 'department_id' => '15'],
            [ 'description' => 'MAPIRIPANA', 'department_id' => '15'],
            [ 'description' => 'MORICHAL', 'department_id' => '15'],
            [ 'description' => 'PANA PANA', 'department_id' => '15'],
            [ 'description' => 'PUERTO COLOMBIA', 'department_id' => '15'],
            [ 'description' => 'SAN FELIPE', 'department_id' => '15'],
            [ 'description' => 'CALAMAR', 'department_id' => '16'],
            [ 'description' => 'EL RETORNO', 'department_id' => '16'],
            [ 'description' => 'MIRAFLOREZ', 'department_id' => '16'],
            [ 'description' => 'SAN JOSÉ DEL GUAVIARE', 'department_id' => '16'],
            [ 'description' => 'ACEVEDO', 'department_id' => '17'],
            [ 'description' => 'AGRADO', 'department_id' => '17'],
            [ 'description' => 'AIPE', 'department_id' => '17'],
            [ 'description' => 'ALGECIRAS', 'department_id' => '17'],
            [ 'description' => 'ALTAMIRA', 'department_id' => '17'],
            [ 'description' => 'BARAYA', 'department_id' => '17'],
            [ 'description' => 'CAMPO ALEGRE', 'department_id' => '17'],
            [ 'description' => 'COLOMBIA', 'department_id' => '17'],
            [ 'description' => 'ELIAS', 'department_id' => '17'],
            [ 'description' => 'GARZÓN', 'department_id' => '17'],
            [ 'description' => 'GIGANTE', 'department_id' => '17'],
            [ 'description' => 'GUADALUPE', 'department_id' => '17'],
            [ 'description' => 'HOBO', 'department_id' => '17'],
            [ 'description' => 'IQUIRA', 'department_id' => '17'],
            [ 'description' => 'ISNOS', 'department_id' => '17'],
            [ 'description' => 'LA ARGENTINA', 'department_id' => '17'],
            [ 'description' => 'LA PLATA', 'department_id' => '17'],
            [ 'description' => 'NATAGA', 'department_id' => '17'],
            [ 'description' => 'NEIVA', 'department_id' => '17'],
            [ 'description' => 'OPORAPA', 'department_id' => '17'],
            [ 'description' => 'PAICOL', 'department_id' => '17'],
            [ 'description' => 'PALERMO', 'department_id' => '17'],
            [ 'description' => 'PALESTINA', 'department_id' => '17'],
            [ 'description' => 'PITAL', 'department_id' => '17'],
            [ 'description' => 'PITALITO', 'department_id' => '17'],
            [ 'description' => 'RIVERA', 'department_id' => '17'],
            [ 'description' => 'SALADO BLANCO', 'department_id' => '17'],
            [ 'description' => 'SAN AGUSTÍN', 'department_id' => '17'],
            [ 'description' => 'SANTA MARIA', 'department_id' => '17'],
            [ 'description' => 'SUAZA', 'department_id' => '17'],
            [ 'description' => 'TARQUI', 'department_id' => '17'],
            [ 'description' => 'TELLO', 'department_id' => '17'],
            [ 'description' => 'TERUEL', 'department_id' => '17'],
            [ 'description' => 'TESALIA', 'department_id' => '17'],
            [ 'description' => 'TIMANA', 'department_id' => '17'],
            [ 'description' => 'VILLAVIEJA', 'department_id' => '17'],
            [ 'description' => 'YAGUARA', 'department_id' => '17'],
            [ 'description' => 'ALBANIA', 'department_id' => '18'],
            [ 'description' => 'BARRANCAS', 'department_id' => '18'],
            [ 'description' => 'DIBULLA', 'department_id' => '18'],
            [ 'description' => 'DISTRACCIÓN', 'department_id' => '18'],
            [ 'description' => 'EL MOLINO', 'department_id' => '18'],
            [ 'description' => 'FONSECA', 'department_id' => '18'],
            [ 'description' => 'HATO NUEVO', 'department_id' => '18'],
            [ 'description' => 'LA JAGUA DEL PILAR', 'department_id' => '18'],
            [ 'description' => 'MAICAO', 'department_id' => '18'],
            [ 'description' => 'MANAURE', 'department_id' => '18'],
            [ 'description' => 'RIOHACHA', 'department_id' => '18'],
            [ 'description' => 'SAN JUAN DEL CESAR', 'department_id' => '18'],
            [ 'description' => 'URIBIA', 'department_id' => '18'],
            [ 'description' => 'URUMITA', 'department_id' => '18'],
            [ 'description' => 'VILLANUEVA', 'department_id' => '18'],
            [ 'description' => 'ALGARROBO', 'department_id' => '19'],
            [ 'description' => 'ARACATACA', 'department_id' => '19'],
            [ 'description' => 'ARIGUANI', 'department_id' => '19'],
            [ 'description' => 'CERRO SAN ANTONIO', 'department_id' => '19'],
            [ 'description' => 'CHIVOLO', 'department_id' => '19'],
            [ 'description' => 'CIENAGA', 'department_id' => '19'],
            [ 'description' => 'CONCORDIA', 'department_id' => '19'],
            [ 'description' => 'EL BANCO', 'department_id' => '19'],
            [ 'description' => 'EL PIÑON', 'department_id' => '19'],
            [ 'description' => 'EL RETEN', 'department_id' => '19'],
            [ 'description' => 'FUNDACION', 'department_id' => '19'],
            [ 'description' => 'GUAMAL', 'department_id' => '19'],
            [ 'description' => 'NUEVA GRANADA', 'department_id' => '19'],
            [ 'description' => 'PEDRAZA', 'department_id' => '19'],
            [ 'description' => 'PIJIÑO DEL CARMEN', 'department_id' => '19'],
            [ 'description' => 'PIVIJAY', 'department_id' => '19'],
            [ 'description' => 'PLATO', 'department_id' => '19'],
            [ 'description' => 'PUEBLO VIEJO', 'department_id' => '19'],
            [ 'description' => 'REMOLINO', 'department_id' => '19'],
            [ 'description' => 'SABANAS DE SAN ANGEL', 'department_id' => '19'],
            [ 'description' => 'SALAMINA', 'department_id' => '19'],
            [ 'description' => 'SAN SEBASTIAN DE BUENAVISTA', 'department_id' => '19'],
            [ 'description' => 'SAN ZENON', 'department_id' => '19'],
            [ 'description' => 'SANTA ANA', 'department_id' => '19'],
            [ 'description' => 'SANTA BARBARA DE PINTO', 'department_id' => '19'],
            [ 'description' => 'SANTA MARTA', 'department_id' => '19'],
            [ 'description' => 'SITIONUEVO', 'department_id' => '19'],
            [ 'description' => 'TENERIFE', 'department_id' => '19'],
            [ 'description' => 'ZAPAYAN', 'department_id' => '19'],
            [ 'description' => 'ZONA BANANERA', 'department_id' => '19'],
            [ 'description' => 'ACACIAS', 'department_id' => '20'],
            [ 'description' => 'BARRANCA DE UPIA', 'department_id' => '20'],
            [ 'description' => 'CABUYARO', 'department_id' => '20'],
            [ 'description' => 'CASTILLA LA NUEVA', 'department_id' => '20'],
            [ 'description' => 'CUBARRAL', 'department_id' => '20'],
            [ 'description' => 'CUMARAL', 'department_id' => '20'],
            [ 'description' => 'EL CALVARIO', 'department_id' => '20'],
            [ 'description' => 'EL CASTILLO', 'department_id' => '20'],
            [ 'description' => 'EL DORADO', 'department_id' => '20'],
            [ 'description' => 'FUENTE DE ORO', 'department_id' => '20'],
            [ 'description' => 'GRANADA', 'department_id' => '20'],
            [ 'description' => 'GUAMAL', 'department_id' => '20'],
            [ 'description' => 'LA MACARENA', 'department_id' => '20'],
            [ 'description' => 'LA URIBE', 'department_id' => '20'],
            [ 'description' => 'LEJANÍAS', 'department_id' => '20'],
            [ 'description' => 'MAPIRIPÁN', 'department_id' => '20'],
            [ 'description' => 'MESETAS', 'department_id' => '20'],
            [ 'description' => 'PUERTO CONCORDIA', 'department_id' => '20'],
            [ 'description' => 'PUERTO GAITÁN', 'department_id' => '20'],
            [ 'description' => 'PUERTO LLERAS', 'department_id' => '20'],
            [ 'description' => 'PUERTO LÓPEZ', 'department_id' => '20'],
            [ 'description' => 'PUERTO RICO', 'department_id' => '20'],
            [ 'description' => 'RESTREPO', 'department_id' => '20'],
            [ 'description' => 'SAN  JUAN DE ARAMA', 'department_id' => '20'],
            [ 'description' => 'SAN CARLOS GUAROA', 'department_id' => '20'],
            [ 'description' => 'SAN JUANITO', 'department_id' => '20'],
            [ 'description' => 'SAN MARTÍN', 'department_id' => '20'],
            [ 'description' => 'VILLAVICENCIO', 'department_id' => '20'],
            [ 'description' => 'VISTA HERMOSA', 'department_id' => '20'],
            [ 'description' => 'ALBAN', 'department_id' => '21'],
            [ 'description' => 'ALDAÑA', 'department_id' => '21'],
            [ 'description' => 'ANCUYA', 'department_id' => '21'],
            [ 'description' => 'ARBOLEDA', 'department_id' => '21'],
            [ 'description' => 'BARBACOAS', 'department_id' => '21'],
            [ 'description' => 'BELEN', 'department_id' => '21'],
            [ 'description' => 'BUESACO', 'department_id' => '21'],
            [ 'description' => 'CHACHAGUI', 'department_id' => '21'],
            [ 'description' => 'COLON (GENOVA)', 'department_id' => '21'],
            [ 'description' => 'CONSACA', 'department_id' => '21'],
            [ 'description' => 'CONTADERO', 'department_id' => '21'],
            [ 'description' => 'CORDOBA', 'department_id' => '21'],
            [ 'description' => 'CUASPUD', 'department_id' => '21'],
            [ 'description' => 'CUMBAL', 'department_id' => '21'],
            [ 'description' => 'CUMBITARA', 'department_id' => '21'],
            [ 'description' => 'EL CHARCO', 'department_id' => '21'],
            [ 'description' => 'EL PEÑOL', 'department_id' => '21'],
            [ 'description' => 'EL ROSARIO', 'department_id' => '21'],
            [ 'description' => 'EL TABLÓN', 'department_id' => '21'],
            [ 'description' => 'EL TAMBO', 'department_id' => '21'],
            [ 'description' => 'FUNES', 'department_id' => '21'],
            [ 'description' => 'GUACHUCAL', 'department_id' => '21'],
            [ 'description' => 'GUAITARILLA', 'department_id' => '21'],
            [ 'description' => 'GUALMATAN', 'department_id' => '21'],
            [ 'description' => 'ILES', 'department_id' => '21'],
            [ 'description' => 'IMUES', 'department_id' => '21'],
            [ 'description' => 'IPIALES', 'department_id' => '21'],
            [ 'description' => 'LA CRUZ', 'department_id' => '21'],
            [ 'description' => 'LA FLORIDA', 'department_id' => '21'],
            [ 'description' => 'LA LLANADA', 'department_id' => '21'],
            [ 'description' => 'LA TOLA', 'department_id' => '21'],
            [ 'description' => 'LA UNION', 'department_id' => '21'],
            [ 'description' => 'LEIVA', 'department_id' => '21'],
            [ 'description' => 'LINARES', 'department_id' => '21'],
            [ 'description' => 'LOS ANDES', 'department_id' => '21'],
            [ 'description' => 'MAGUI', 'department_id' => '21'],
            [ 'description' => 'MALLAMA', 'department_id' => '21'],
            [ 'description' => 'MOSQUEZA', 'department_id' => '21'],
            [ 'description' => 'NARIÑO', 'department_id' => '21'],
            [ 'description' => 'OLAYA HERRERA', 'department_id' => '21'],
            [ 'description' => 'OSPINA', 'department_id' => '21'],
            [ 'description' => 'PASTO', 'department_id' => '21'],
            [ 'description' => 'PIZARRO', 'department_id' => '21'],
            [ 'description' => 'POLICARPA', 'department_id' => '21'],
            [ 'description' => 'POTOSI', 'department_id' => '21'],
            [ 'description' => 'PROVIDENCIA', 'department_id' => '21'],
            [ 'description' => 'PUERRES', 'department_id' => '21'],
            [ 'description' => 'PUPIALES', 'department_id' => '21'],
            [ 'description' => 'RICAURTE', 'department_id' => '21'],
            [ 'description' => 'ROBERTO PAYAN', 'department_id' => '21'],
            [ 'description' => 'SAMANIEGO', 'department_id' => '21'],
            [ 'description' => 'SAN BERNARDO', 'department_id' => '21'],
            [ 'description' => 'SAN LORENZO', 'department_id' => '21'],
            [ 'description' => 'SAN PABLO', 'department_id' => '21'],
            [ 'description' => 'SAN PEDRO DE CARTAGO', 'department_id' => '21'],
            [ 'description' => 'SANDONA', 'department_id' => '21'],
            [ 'description' => 'SANTA BARBARA', 'department_id' => '21'],
            [ 'description' => 'SANTACRUZ', 'department_id' => '21'],
            [ 'description' => 'SAPUYES', 'department_id' => '21'],
            [ 'description' => 'TAMINANGO', 'department_id' => '21'],
            [ 'description' => 'TANGUA', 'department_id' => '21'],
            [ 'description' => 'TUMACO', 'department_id' => '21'],
            [ 'description' => 'TUQUERRES', 'department_id' => '21'],
            [ 'description' => 'YACUANQUER', 'department_id' => '21'],
            [ 'description' => 'ABREGO', 'department_id' => '22'],
            [ 'description' => 'ARBOLEDAS', 'department_id' => '22'],
            [ 'description' => 'BOCHALEMA', 'department_id' => '22'],
            [ 'description' => 'BUCARASICA', 'department_id' => '22'],
            [ 'description' => 'CÁCHIRA', 'department_id' => '22'],
            [ 'description' => 'CÁCOTA', 'department_id' => '22'],
            [ 'description' => 'CHINÁCOTA', 'department_id' => '22'],
            [ 'description' => 'CHITAGÁ', 'department_id' => '22'],
            [ 'description' => 'CONVENCIÓN', 'department_id' => '22'],
            [ 'description' => 'CÚCUTA', 'department_id' => '22'],
            [ 'description' => 'CUCUTILLA', 'department_id' => '22'],
            [ 'description' => 'DURANIA', 'department_id' => '22'],
            [ 'description' => 'EL CARMEN', 'department_id' => '22'],
            [ 'description' => 'EL TARRA', 'department_id' => '22'],
            [ 'description' => 'EL ZULIA', 'department_id' => '22'],
            [ 'description' => 'GRAMALOTE', 'department_id' => '22'],
            [ 'description' => 'HACARI', 'department_id' => '22'],
            [ 'description' => 'HERRÁN', 'department_id' => '22'],
            [ 'description' => 'LA ESPERANZA', 'department_id' => '22'],
            [ 'description' => 'LA PLAYA', 'department_id' => '22'],
            [ 'description' => 'LABATECA', 'department_id' => '22'],
            [ 'description' => 'LOS PATIOS', 'department_id' => '22'],
            [ 'description' => 'LOURDES', 'department_id' => '22'],
            [ 'description' => 'MUTISCUA', 'department_id' => '22'],
            [ 'description' => 'OCAÑA', 'department_id' => '22'],
            [ 'description' => 'PAMPLONA', 'department_id' => '22'],
            [ 'description' => 'PAMPLONITA', 'department_id' => '22'],
            [ 'description' => 'PUERTO SANTANDER', 'department_id' => '22'],
            [ 'description' => 'RAGONVALIA', 'department_id' => '22'],
            [ 'description' => 'SALAZAR', 'department_id' => '22'],
            [ 'description' => 'SAN CALIXTO', 'department_id' => '22'],
            [ 'description' => 'SAN CAYETANO', 'department_id' => '22'],
            [ 'description' => 'SANTIAGO', 'department_id' => '22'],
            [ 'description' => 'SARDINATA', 'department_id' => '22'],
            [ 'description' => 'SILOS', 'department_id' => '22'],
            [ 'description' => 'TEORAMA', 'department_id' => '22'],
            [ 'description' => 'TIBÚ', 'department_id' => '22'],
            [ 'description' => 'TOLEDO', 'department_id' => '22'],
            [ 'description' => 'VILLA CARO', 'department_id' => '22'],
            [ 'description' => 'VILLA DEL ROSARIO', 'department_id' => '22'],
            [ 'description' => 'COLÓN', 'department_id' => '23'],
            [ 'description' => 'MOCOA', 'department_id' => '23'],
            [ 'description' => 'ORITO', 'department_id' => '23'],
            [ 'description' => 'PUERTO ASÍS', 'department_id' => '23'],
            [ 'description' => 'PUERTO CAYCEDO', 'department_id' => '23'],
            [ 'description' => 'PUERTO GUZMÁN', 'department_id' => '23'],
            [ 'description' => 'PUERTO LEGUÍZAMO', 'department_id' => '23'],
            [ 'description' => 'SAN FRANCISCO', 'department_id' => '23'],
            [ 'description' => 'SAN MIGUEL', 'department_id' => '23'],
            [ 'description' => 'SANTIAGO', 'department_id' => '23'],
            [ 'description' => 'SIBUNDOY', 'department_id' => '23'],
            [ 'description' => 'VALLE DEL GUAMUEZ', 'department_id' => '23'],
            [ 'description' => 'VILLAGARZÓN', 'department_id' => '23'],
            [ 'description' => 'ARMENIA', 'department_id' => '24'],
            [ 'description' => 'BUENAVISTA', 'department_id' => '24'],
            [ 'description' => 'CALARCÁ', 'department_id' => '24'],
            [ 'description' => 'CIRCASIA', 'department_id' => '24'],
            [ 'description' => 'CÓRDOBA', 'department_id' => '24'],
            [ 'description' => 'FILANDIA', 'department_id' => '24'],
            [ 'description' => 'GÉNOVA', 'department_id' => '24'],
            [ 'description' => 'LA TEBAIDA', 'department_id' => '24'],
            [ 'description' => 'MONTENEGRO', 'department_id' => '24'],
            [ 'description' => 'PIJAO', 'department_id' => '24'],
            [ 'description' => 'QUIMBAYA', 'department_id' => '24'],
            [ 'description' => 'SALENTO', 'department_id' => '24'],
            [ 'description' => 'APIA', 'department_id' => '25'],
            [ 'description' => 'BALBOA', 'department_id' => '25'],
            [ 'description' => 'BELÉN DE UMBRÍA', 'department_id' => '25'],
            [ 'description' => 'DOS QUEBRADAS', 'department_id' => '25'],
            [ 'description' => 'GUATICA', 'department_id' => '25'],
            [ 'description' => 'LA CELIA', 'department_id' => '25'],
            [ 'description' => 'LA VIRGINIA', 'department_id' => '25'],
            [ 'description' => 'MARSELLA', 'department_id' => '25'],
            [ 'description' => 'MISTRATO', 'department_id' => '25'],
            [ 'description' => 'PEREIRA', 'department_id' => '25'],
            [ 'description' => 'PUEBLO RICO', 'department_id' => '25'],
            [ 'description' => 'QUINCHÍA', 'department_id' => '25'],
            [ 'description' => 'SANTA ROSA DE CABAL', 'department_id' => '25'],
            [ 'description' => 'SANTUARIO', 'department_id' => '25'],
            [ 'description' => 'PROVIDENCIA', 'department_id' => '26'],
            [ 'description' => 'SAN ANDRES', 'department_id' => '26'],
            [ 'description' => 'SANTA CATALINA', 'department_id' => '26'],
            [ 'description' => 'AGUADA', 'department_id' => '27'],
            [ 'description' => 'ALBANIA', 'department_id' => '27'],
            [ 'description' => 'ARATOCA', 'department_id' => '27'],
            [ 'description' => 'BARBOSA', 'department_id' => '27'],
            [ 'description' => 'BARICHARA', 'department_id' => '27'],
            [ 'description' => 'BARRANCABERMEJA', 'department_id' => '27'],
            [ 'description' => 'BETULIA', 'department_id' => '27'],
            [ 'description' => 'BOLÍVAR', 'department_id' => '27'],
            [ 'description' => 'BUCARAMANGA', 'department_id' => '27'],
            [ 'description' => 'CABRERA', 'department_id' => '27'],
            [ 'description' => 'CALIFORNIA', 'department_id' => '27'],
            [ 'description' => 'CAPITANEJO', 'department_id' => '27'],
            [ 'description' => 'CARCASI', 'department_id' => '27'],
            [ 'description' => 'CEPITA', 'department_id' => '27'],
            [ 'description' => 'CERRITO', 'department_id' => '27'],
            [ 'description' => 'CHARALÁ', 'department_id' => '27'],
            [ 'description' => 'CHARTA', 'department_id' => '27'],
            [ 'description' => 'CHIMA', 'department_id' => '27'],
            [ 'description' => 'CHIPATÁ', 'department_id' => '27'],
            [ 'description' => 'CIMITARRA', 'department_id' => '27'],
            [ 'description' => 'CONCEPCIÓN', 'department_id' => '27'],
            [ 'description' => 'CONFINES', 'department_id' => '27'],
            [ 'description' => 'CONTRATACIÓN', 'department_id' => '27'],
            [ 'description' => 'COROMORO', 'department_id' => '27'],
            [ 'description' => 'CURITÍ', 'department_id' => '27'],
            [ 'description' => 'EL CARMEN', 'department_id' => '27'],
            [ 'description' => 'EL GUACAMAYO', 'department_id' => '27'],
            [ 'description' => 'EL PEÑÓN', 'department_id' => '27'],
            [ 'description' => 'EL PLAYÓN', 'department_id' => '27'],
            [ 'description' => 'ENCINO', 'department_id' => '27'],
            [ 'description' => 'ENCISO', 'department_id' => '27'],
            [ 'description' => 'FLORIÁN', 'department_id' => '27'],
            [ 'description' => 'FLORIDABLANCA', 'department_id' => '27'],
            [ 'description' => 'GALÁN', 'department_id' => '27'],
            [ 'description' => 'GAMBITA', 'department_id' => '27'],
            [ 'description' => 'GIRÓN', 'department_id' => '27'],
            [ 'description' => 'GUACA', 'department_id' => '27'],
            [ 'description' => 'GUADALUPE', 'department_id' => '27'],
            [ 'description' => 'GUAPOTA', 'department_id' => '27'],
            [ 'description' => 'GUAVATÁ', 'department_id' => '27'],
            [ 'description' => 'GUEPSA', 'department_id' => '27'],
            [ 'description' => 'HATO', 'department_id' => '27'],
            [ 'description' => 'JESÚS MARIA', 'department_id' => '27'],
            [ 'description' => 'JORDÁN', 'department_id' => '27'],
            [ 'description' => 'LA BELLEZA', 'department_id' => '27'],
            [ 'description' => 'LA PAZ', 'department_id' => '27'],
            [ 'description' => 'LANDAZURI', 'department_id' => '27'],
            [ 'description' => 'LEBRIJA', 'department_id' => '27'],
            [ 'description' => 'LOS SANTOS', 'department_id' => '27'],
            [ 'description' => 'MACARAVITA', 'department_id' => '27'],
            [ 'description' => 'MÁLAGA', 'department_id' => '27'],
            [ 'description' => 'MATANZA', 'department_id' => '27'],
            [ 'description' => 'MOGOTES', 'department_id' => '27'],
            [ 'description' => 'MOLAGAVITA', 'department_id' => '27'],
            [ 'description' => 'OCAMONTE', 'department_id' => '27'],
            [ 'description' => 'OIBA', 'department_id' => '27'],
            [ 'description' => 'ONZAGA', 'department_id' => '27'],
            [ 'description' => 'PALMAR', 'department_id' => '27'],
            [ 'description' => 'PALMAS DEL SOCORRO', 'department_id' => '27'],
            [ 'description' => 'PÁRAMO', 'department_id' => '27'],
            [ 'description' => 'PIEDECUESTA', 'department_id' => '27'],
            [ 'description' => 'PINCHOTE', 'department_id' => '27'],
            [ 'description' => 'PUENTE NACIONAL', 'department_id' => '27'],
            [ 'description' => 'PUERTO PARRA', 'department_id' => '27'],
            [ 'description' => 'PUERTO WILCHES', 'department_id' => '27'],
            [ 'description' => 'RIONEGRO', 'department_id' => '27'],
            [ 'description' => 'SABANA DE TORRES', 'department_id' => '27'],
            [ 'description' => 'SAN ANDRÉS', 'department_id' => '27'],
            [ 'description' => 'SAN BENITO', 'department_id' => '27'],
            [ 'description' => 'SAN GIL', 'department_id' => '27'],
            [ 'description' => 'SAN JOAQUÍN', 'department_id' => '27'],
            [ 'description' => 'SAN JOSÉ DE MIRANDA', 'department_id' => '27'],
            [ 'description' => 'SAN MIGUEL', 'department_id' => '27'],
            [ 'description' => 'SAN VICENTE DE CHUCURÍ', 'department_id' => '27'],
            [ 'description' => 'SANTA BÁRBARA', 'department_id' => '27'],
            [ 'description' => 'SANTA HELENA', 'department_id' => '27'],
            [ 'description' => 'SIMACOTA', 'department_id' => '27'],
            [ 'description' => 'SOCORRO', 'department_id' => '27'],
            [ 'description' => 'SUAITA', 'department_id' => '27'],
            [ 'description' => 'SUCRE', 'department_id' => '27'],
            [ 'description' => 'SURATA', 'department_id' => '27'],
            [ 'description' => 'TONA', 'department_id' => '27'],
            [ 'description' => 'VALLE SAN JOSÉ', 'department_id' => '27'],
            [ 'description' => 'VÉLEZ', 'department_id' => '27'],
            [ 'description' => 'VETAS', 'department_id' => '27'],
            [ 'description' => 'VILLANUEVA', 'department_id' => '27'],
            [ 'description' => 'ZAPATOCA', 'department_id' => '27'],
            [ 'description' => 'BUENAVISTA', 'department_id' => '28'],
            [ 'description' => 'CAIMITO', 'department_id' => '28'],
            [ 'description' => 'CHALÁN', 'department_id' => '28'],
            [ 'description' => 'COLOSO', 'department_id' => '28'],
            [ 'description' => 'COROZAL', 'department_id' => '28'],
            [ 'description' => 'EL ROBLE', 'department_id' => '28'],
            [ 'description' => 'GALERAS', 'department_id' => '28'],
            [ 'description' => 'GUARANDA', 'department_id' => '28'],
            [ 'description' => 'LA UNIÓN', 'department_id' => '28'],
            [ 'description' => 'LOS PALMITOS', 'department_id' => '28'],
            [ 'description' => 'MAJAGUAL', 'department_id' => '28'],
            [ 'description' => 'MORROA', 'department_id' => '28'],
            [ 'description' => 'OVEJAS', 'department_id' => '28'],
            [ 'description' => 'PALMITO', 'department_id' => '28'],
            [ 'description' => 'SAMPUES', 'department_id' => '28'],
            [ 'description' => 'SAN BENITO ABAD', 'department_id' => '28'],
            [ 'description' => 'SAN JUAN DE BETULIA', 'department_id' => '28'],
            [ 'description' => 'SAN MARCOS', 'department_id' => '28'],
            [ 'description' => 'SAN ONOFRE', 'department_id' => '28'],
            [ 'description' => 'SAN PEDRO', 'department_id' => '28'],
            [ 'description' => 'SINCÉ', 'department_id' => '28'],
            [ 'description' => 'SINCELEJO', 'department_id' => '28'],
            [ 'description' => 'SUCRE', 'department_id' => '28'],
            [ 'description' => 'TOLÚ', 'department_id' => '28'],
            [ 'description' => 'TOLUVIEJO', 'department_id' => '28'],
            [ 'description' => 'ALPUJARRA', 'department_id' => '29'],
            [ 'description' => 'ALVARADO', 'department_id' => '29'],
            [ 'description' => 'AMBALEMA', 'department_id' => '29'],
            [ 'description' => 'ANZOATEGUI', 'department_id' => '29'],
            [ 'description' => 'ARMERO (GUAYABAL)', 'department_id' => '29'],
            [ 'description' => 'ATACO', 'department_id' => '29'],
            [ 'description' => 'CAJAMARCA', 'department_id' => '29'],
            [ 'description' => 'CARMEN DE APICALÁ', 'department_id' => '29'],
            [ 'description' => 'CASABIANCA', 'department_id' => '29'],
            [ 'description' => 'CHAPARRAL', 'department_id' => '29'],
            [ 'description' => 'COELLO', 'department_id' => '29'],
            [ 'description' => 'COYAIMA', 'department_id' => '29'],
            [ 'description' => 'CUNDAY', 'department_id' => '29'],
            [ 'description' => 'DOLORES', 'department_id' => '29'],
            [ 'description' => 'ESPINAL', 'department_id' => '29'],
            [ 'description' => 'FALÁN', 'department_id' => '29'],
            [ 'description' => 'FLANDES', 'department_id' => '29'],
            [ 'description' => 'FRESNO', 'department_id' => '29'],
            [ 'description' => 'GUAMO', 'department_id' => '29'],
            [ 'description' => 'HERVEO', 'department_id' => '29'],
            [ 'description' => 'HONDA', 'department_id' => '29'],
            [ 'description' => 'IBAGUÉ', 'department_id' => '29'],
            [ 'description' => 'ICONONZO', 'department_id' => '29'],
            [ 'description' => 'LÉRIDA', 'department_id' => '29'],
            [ 'description' => 'LÍBANO', 'department_id' => '29'],
            [ 'description' => 'MARIQUITA', 'department_id' => '29'],
            [ 'description' => 'MELGAR', 'department_id' => '29'],
            [ 'description' => 'MURILLO', 'department_id' => '29'],
            [ 'description' => 'NATAGAIMA', 'department_id' => '29'],
            [ 'description' => 'ORTEGA', 'department_id' => '29'],
            [ 'description' => 'PALOCABILDO', 'department_id' => '29'],
            [ 'description' => 'PIEDRAS PLANADAS', 'department_id' => '29'],
            [ 'description' => 'PRADO', 'department_id' => '29'],
            [ 'description' => 'PURIFICACIÓN', 'department_id' => '29'],
            [ 'description' => 'RIOBLANCO', 'department_id' => '29'],
            [ 'description' => 'RONCESVALLES', 'department_id' => '29'],
            [ 'description' => 'ROVIRA', 'department_id' => '29'],
            [ 'description' => 'SALDAÑA', 'department_id' => '29'],
            [ 'description' => 'SAN ANTONIO', 'department_id' => '29'],
            [ 'description' => 'SAN LUIS', 'department_id' => '29'],
            [ 'description' => 'SANTA ISABEL', 'department_id' => '29'],
            [ 'description' => 'SUÁREZ', 'department_id' => '29'],
            [ 'description' => 'VALLE DE SAN JUAN', 'department_id' => '29'],
            [ 'description' => 'VENADILLO', 'department_id' => '29'],
            [ 'description' => 'VILLAHERMOSA', 'department_id' => '29'],
            [ 'description' => 'VILLARRICA', 'department_id' => '29'],
            [ 'description' => 'ALCALÁ', 'department_id' => '30'],
            [ 'description' => 'ANDALUCÍA', 'department_id' => '30'],
            [ 'description' => 'ANSERMA NUEVO', 'department_id' => '30'],
            [ 'description' => 'ARGELIA', 'department_id' => '30'],
            [ 'description' => 'BOLÍVAR', 'department_id' => '30'],
            [ 'description' => 'BUENAVENTURA', 'department_id' => '30'],
            [ 'description' => 'BUGA', 'department_id' => '30'],
            [ 'description' => 'BUGALAGRANDE', 'department_id' => '30'],
            [ 'description' => 'CAICEDONIA', 'department_id' => '30'],
            [ 'description' => 'CALI', 'department_id' => '30'],
            [ 'description' => 'CALIMA (DARIEN)', 'department_id' => '30'],
            [ 'description' => 'CANDELARIA', 'department_id' => '30'],
            [ 'description' => 'CARTAGO', 'department_id' => '30'],
            [ 'description' => 'DAGUA', 'department_id' => '30'],
            [ 'description' => 'EL AGUILA', 'department_id' => '30'],
            [ 'description' => 'EL CAIRO', 'department_id' => '30'],
            [ 'description' => 'EL CERRITO', 'department_id' => '30'],
            [ 'description' => 'EL DOVIO', 'department_id' => '30'],
            [ 'description' => 'FLORIDA', 'department_id' => '30'],
            [ 'description' => 'GINEBRA GUACARI', 'department_id' => '30'],
            [ 'description' => 'JAMUNDÍ', 'department_id' => '30'],
            [ 'description' => 'LA CUMBRE', 'department_id' => '30'],
            [ 'description' => 'LA UNIÓN', 'department_id' => '30'],
            [ 'description' => 'LA VICTORIA', 'department_id' => '30'],
            [ 'description' => 'OBANDO', 'department_id' => '30'],
            [ 'description' => 'PALMIRA', 'department_id' => '30'],
            [ 'description' => 'PRADERA', 'department_id' => '30'],
            [ 'description' => 'RESTREPO', 'department_id' => '30'],
            [ 'description' => 'RIO FRÍO', 'department_id' => '30'],
            [ 'description' => 'ROLDANILLO', 'department_id' => '30'],
            [ 'description' => 'SAN PEDRO', 'department_id' => '30'],
            [ 'description' => 'SEVILLA', 'department_id' => '30'],
            [ 'description' => 'TORO', 'department_id' => '30'],
            [ 'description' => 'TRUJILLO', 'department_id' => '30'],
            [ 'description' => 'TULÚA', 'department_id' => '30'],
            [ 'description' => 'ULLOA', 'department_id' => '30'],
            [ 'description' => 'VERSALLES', 'department_id' => '30'],
            [ 'description' => 'VIJES', 'department_id' => '30'],
            [ 'description' => 'YOTOCO', 'department_id' => '30'],
            [ 'description' => 'YUMBO', 'department_id' => '30'],
            [ 'description' => 'ZARZAL', 'department_id' => '30'],
            [ 'description' => 'CARURÚ', 'department_id' => '31'],
            [ 'description' => 'MITÚ', 'department_id' => '31'],
            [ 'description' => 'PACOA', 'department_id' => '31'],
            [ 'description' => 'PAPUNAUA', 'department_id' => '31'],
            [ 'description' => 'TARAIRA', 'department_id' => '31'],
            [ 'description' => 'YAVARATÉ', 'department_id' => '31'],
            [ 'description' => 'CUMARIBO', 'department_id' => '32'],
            [ 'description' => 'LA PRIMAVERA', 'department_id' => '32'],
            [ 'description' => 'PUERTO CARREÑO', 'department_id' => '32'],
            [ 'description' => 'SANTA ROSALIA', 'department_id' => '32'],
        ];

        foreach ($cities as $key => $value) {
            City::create($value);
        }
    }
}
